// `addroid init` の冪等性と境界条件を検証する。
//
// すべて ADDROID_HOME を一時ディレクトリに切り替えて実行し、ユーザーの本物の
// ~/.addroid を一切触らない。E2E smoke-test の前提となる「クリーンな $HOME で
// init が壊れず、繰り返しても破壊しない」ことの自動検証である。

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { runInit } from "../commands/init.js";

interface Captured {
  stdout: string;
  stderr: string;
}

async function capture(
  fn: () => Promise<number>
): Promise<{ code: number; out: Captured }> {
  const out: Captured = { stdout: "", stderr: "" };
  const origOut = process.stdout.write.bind(process.stdout);
  const origErr = process.stderr.write.bind(process.stderr);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  process.stdout.write = ((chunk: any) => {
    out.stdout += typeof chunk === "string" ? chunk : chunk.toString();
    return true;
  }) as typeof process.stdout.write;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  process.stderr.write = ((chunk: any) => {
    out.stderr += typeof chunk === "string" ? chunk : chunk.toString();
    return true;
  }) as typeof process.stderr.write;
  try {
    const code = await fn();
    return { code, out };
  } finally {
    process.stdout.write = origOut;
    process.stderr.write = origErr;
  }
}

async function withTempHome<T>(
  fn: (home: string) => Promise<T>
): Promise<T> {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "addroid-init-"));
  const prev = process.env.ADDROID_HOME;
  const prevMetaCliBin = process.env.ADDROID_META_CLI_BIN;
  const prevPath = process.env.PATH;
  const binDir = path.join(dir, "bin");
  fs.mkdirSync(binDir, { recursive: true });
  const codexBin = path.join(binDir, "codex");
  fs.writeFileSync(codexBin, "#!/bin/sh\necho 'codex 0.0.0'\n", {
    encoding: "utf8",
    mode: 0o755,
  });
  process.env.ADDROID_HOME = dir;
  process.env.PATH = [binDir, prevPath].filter(Boolean).join(path.delimiter);
  try {
    return await fn(dir);
  } finally {
    if (prev === undefined) delete process.env.ADDROID_HOME;
    else process.env.ADDROID_HOME = prev;
    if (prevMetaCliBin === undefined) delete process.env.ADDROID_META_CLI_BIN;
    else process.env.ADDROID_META_CLI_BIN = prevMetaCliBin;
    if (prevPath === undefined) delete process.env.PATH;
    else process.env.PATH = prevPath;
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

test("init は ADDROID_HOME 配下に storage / logs / run を作成し config / secrets stub を生成する", async () => {
  await withTempHome(async (home) => {
    const { code, out } = await capture(() => runInit([]));
    assert.equal(code, 0, out.stdout + out.stderr);

    for (const sub of ["storage", "logs", "run"]) {
      const stat = fs.statSync(path.join(home, sub));
      assert.ok(stat.isDirectory(), `${sub} should be a directory`);
    }

    const configRaw = fs.readFileSync(path.join(home, "config.yaml"), "utf8");
    assert.match(configRaw, /version: 1/);
    assert.match(configRaw, /slug: default/);
    assert.match(configRaw, /executionMode: proposal/);

    const secretsPath = path.join(home, "secrets.local.yaml");
    const secretsStat = fs.statSync(secretsPath);
    assert.ok(secretsStat.isFile());
    if (process.platform !== "win32") {
      // POSIX 上では secrets stub は 0600 で書かれる。
      assert.equal(secretsStat.mode & 0o777, 0o600);
    }

    assert.match(out.stdout, /\[addroid init\]/);
    assert.match(out.stdout, /config 0040.*\(updated\)|config\s+: .*\(updated\)/);
    assert.match(out.stdout, /secrets file/);
  });
});

test("init はセットアップ後に使う addroid command wrapper を作成する", async () => {
  await withTempHome(async (home) => {
    const { code, out } = await capture(() => runInit([]));
    assert.equal(code, 0, out.stdout + out.stderr);

    const commandPath = path.join(home, "bin", "addroid");
    const aliasPath = path.join(home, "bin", "addroid-cli");
    const raw = fs.readFileSync(commandPath, "utf8");
    const aliasRaw = fs.readFileSync(aliasPath, "utf8");
    assert.match(raw, /^#!\/bin\/sh/);
    assert.match(raw, /Generated by addroid init/);
    assert.match(raw, /bin\/addroid\.cjs/);
    assert.equal(aliasRaw, raw);
    if (process.platform !== "win32") {
      assert.equal(fs.statSync(commandPath).mode & 0o777, 0o755);
    }
    assert.match(out.stdout, /CLI command setup:/);
  });
});

test("init は既存のユーザー管理 addroid command を上書きしない", async () => {
  await withTempHome(async (home) => {
    const binDir = path.join(home, "bin");
    fs.mkdirSync(binDir, { recursive: true });
    const commandPath = path.join(binDir, "addroid");
    fs.writeFileSync(commandPath, "#!/bin/sh\necho custom\n", { mode: 0o755 });

    const { code, out } = await capture(() => runInit([]));
    assert.equal(code, 0, out.stdout + out.stderr);
    assert.equal(fs.readFileSync(commandPath, "utf8"), "#!/bin/sh\necho custom\n");
    assert.match(out.stdout, /skipped \(existing addroid command was not created by init\)/);
  });
});

test("init は二回目の実行で破壊的更新を行わない (config / secrets を保持)", async () => {
  await withTempHome(async (home) => {
    {
      const { code } = await capture(() => runInit([]));
      assert.equal(code, 0);
    }

    // ユーザーが手で値を書き換えたと仮定して上書きする。
    const configPath = path.join(home, "config.yaml");
    const original = fs.readFileSync(configPath, "utf8");
    const edited = original.replace("slug: default", "slug: my-team");
    fs.writeFileSync(configPath, edited, "utf8");
    const editedStat = fs.statSync(configPath);

    const secretsPath = path.join(home, "secrets.local.yaml");
    fs.writeFileSync(secretsPath, "github_oauth_client_secret: redacted\n", {
      encoding: "utf8",
      mode: 0o600,
    });
    const secretsContent = fs.readFileSync(secretsPath, "utf8");

    const { code, out } = await capture(() => runInit([]));
    assert.equal(code, 0, out.stdout + out.stderr);

    const after = fs.readFileSync(configPath, "utf8");
    assert.match(after, /slug: my-team/, "user-edited slug must be preserved");

    const afterStat = fs.statSync(configPath);
    // unchanged の場合 mtime はそのままだが、別の事情で書き換わっても致命的ではない。
    // ここでは「内容が保持されていること」を主張するに留める。
    void editedStat;

    const secretsAfter = fs.readFileSync(secretsPath, "utf8");
    assert.equal(secretsAfter, secretsContent, "existing secrets file must be left as-is");
    assert.match(out.stdout, /\(left as-is\)/);

    void afterStat;
  });
});

test("init は executionMode を再 init で黙って戻さない", async () => {
  await withTempHome(async (home) => {
    {
      const { code } = await capture(() => runInit([]));
      assert.equal(code, 0);
    }
    const configPath = path.join(home, "config.yaml");
    const original = fs.readFileSync(configPath, "utf8");
    const edited = original.replace("executionMode: proposal", "executionMode: auto_apply");
    fs.writeFileSync(configPath, edited, "utf8");

    const { code, out } = await capture(() => runInit([]));
    assert.equal(code, 0, out.stdout + out.stderr);
    const after = fs.readFileSync(configPath, "utf8");
    assert.match(after, /executionMode: auto_apply/);
  });
});

test("init は不正な config.yaml を検出して exit 1 で停止し、ファイルを破壊しない", async () => {
  await withTempHome(async (home) => {
    fs.mkdirSync(home, { recursive: true });
    const configPath = path.join(home, "config.yaml");
    const broken = "version: 1\nworkspace:\n  slug: 1\n"; // slug は string 必須
    fs.writeFileSync(configPath, broken, "utf8");

    const { code, out } = await capture(() => runInit([]));
    assert.equal(code, 1);
    assert.match(out.stderr, /config\.yaml がスキーマと一致しません|スキーマと一致しません/);

    // 元のファイルは破壊されない (init は読めない config を上書きしない契約)。
    const after = fs.readFileSync(configPath, "utf8");
    assert.equal(after, broken);
  });
});

test("init は DATABASE_URL の有無で database.urlRef を再評価する", async () => {
  await withTempHome(async (home) => {
    const prev = process.env.DATABASE_URL;
    delete process.env.DATABASE_URL;
    try {
      const { code } = await capture(() => runInit([]));
      assert.equal(code, 0);
      const config = fs.readFileSync(path.join(home, "config.yaml"), "utf8");
      assert.match(config, /urlRef: \.env\.local/);
    } finally {
      if (prev !== undefined) process.env.DATABASE_URL = prev;
    }

    process.env.DATABASE_URL = "postgres://localhost:5432/addroid_test";
    try {
      const { code } = await capture(() => runInit([]));
      assert.equal(code, 0);
      const config = fs.readFileSync(path.join(home, "config.yaml"), "utf8");
      assert.match(config, /urlRef: \(env\)/);
    } finally {
      if (prev === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prev;
    }
  });
});

test("init は引き継いだ ENCRYPTION_KEY / DATABASE_URL を再利用したら警告する", async () => {
  await withTempHome(async (home) => {
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    delete process.env.DATABASE_URL;
    delete process.env.ENCRYPTION_KEY;
    // 配布元の .env をそのまま受け取った状態 (placeholder ではない実値) を作る。
    fs.writeFileSync(
      path.join(home, ".env"),
      [
        "DATABASE_URL=postgresql://addroid:inherited@localhost:5432/addroid",
        "ENCRYPTION_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
        "",
      ].join("\n"),
      { encoding: "utf8", mode: 0o600 }
    );
    try {
      const { out } = await capture(() =>
        runInit(["--yes", "--non-interactive", "--skip-deps"])
      );
      assert.match(out.stdout, /warning: 既存の .*ENCRYPTION_KEY/);
      assert.match(out.stdout, /他者から受け取った場合は使い続けないでください/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init は初期設定済みなら無印の対話再実行を状態表示だけで終了する", async () => {
  await withTempHome(async (home) => {
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    process.env.DATABASE_URL = "postgresql://addroid:secret@localhost:5432/addroid";
    process.env.ENCRYPTION_KEY = "AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=";
    try {
      {
        const { code } = await capture(() => runInit([], { isTTY: false }));
        assert.equal(code, 0);
      }

      const authCalls: string[][] = [];
      const { code, out } = await capture(() =>
        runInit([], {
          isTTY: true,
          prompt: async () => {
            throw new Error("prompt should not run for already initialized default init");
          },
          confirm: async () => {
            throw new Error("confirm should not run for already initialized default init");
          },
          runCommand: (cmd, args) => {
            if (cmd === "sh" && args.join(" ").includes("command -v addroid")) {
              return { status: 0, stdout: "/usr/local/bin/addroid\n", stderr: "" };
            }
            return { status: 0, stdout: "", stderr: "" };
          },
          runAuthCommand: async (args) => {
            authCalls.push(args);
            return 0;
          },
          readAuthState: async () => ({
            checked: true,
            metaConnected: true,
            llmProviders: ["codex"],
          }),
        })
      );

      assert.equal(code, 0, out.stdout + out.stderr);
      assert.match(out.stdout, /already initialized/);
      assert.match(out.stdout, /Meta Token\s+: configured/);
      assert.match(out.stdout, /LLM Provider\s+: codex/);
      assert.match(out.stdout, /よく使うコマンド:/);
      assert.match(out.stdout, /addroid chat\s+# チャットで/);
      assert.match(out.stdout, /addroid start\s+# 常駐サービス/);
      assert.match(out.stdout, /addroid open\s+# Web UI/);
      assert.match(out.stdout, /接続を直すとき:/);
      assert.match(out.stdout, /addroid connect meta/);
      assert.match(out.stdout, /addroid connect github/);
      assert.match(out.stdout, /addroid connect ai/);
      assert.doesNotMatch(out.stdout, /Maintenance:/);
      assert.doesNotMatch(out.stdout, /addroid init --interactive --reauth-llm/);
      assert.deepEqual(authCalls, []);
      assert.ok(fs.existsSync(path.join(home, "config.yaml")));
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init は初期設定済みでも addroid コマンド未検出なら checkout CLI link を案内して実行する", async () => {
  await withTempHome(async (home) => {
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    process.env.DATABASE_URL = "postgresql://addroid:secret@localhost:5432/addroid";
    process.env.ENCRYPTION_KEY = "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAw=";
    try {
      {
        const { code } = await capture(() => runInit([], { isTTY: false }));
        assert.equal(code, 0);
      }

      const calls: string[] = [];
      const { code, out } = await capture(() =>
        runInit([], {
          isTTY: true,
          confirm: async () => true,
          runCommand: (cmd, args) => {
            calls.push([cmd, ...args].join(" "));
            return { status: 0, stdout: "", stderr: "" };
          },
          readAuthState: async () => ({
            checked: true,
            metaConnected: true,
            metaAccountSelected: true,
            githubConnected: true,
            opsRepoLinked: true,
            llmProviders: ["codex"],
          }),
        })
      );

      assert.equal(code, 0, out.stdout + out.stderr);
      assert.deepEqual(calls, []);
      assert.match(fs.readFileSync(path.join(home, "bin", "addroid"), "utf8"), /Generated by addroid init/);
      assert.match(out.stdout, /already initialized/);
      assert.match(out.stdout, /CLI command setup:/);
      assert.match(out.stdout, /addroid\s+: (created\/updated|available)/);
      assert.match(out.stdout, /addroid chat\s+# チャットで/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --reauth-llm は初期セットアップをやり直さず LLM だけ再接続できる", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    process.env.DATABASE_URL = "postgresql://addroid:secret@localhost:5432/addroid";
    process.env.ENCRYPTION_KEY = "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=";
    const authCalls: string[][] = [];
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--interactive",
            "--skip-deps",
            "--skip-db-create",
            "--skip-db-push",
            "--env-file",
            envFile,
            "--reauth-llm",
          ],
          {
            isTTY: true,
            prompt: async (question, defaultValue = "") => {
              assert.doesNotMatch(question, /この AdDroid インスタンスの名前|DATABASE_URL/);
              return defaultValue;
            },
            selectOption: async () => "codex-app-server",
            runAuthCommand: async (args) => {
              authCalls.push(args);
              return 0;
            },
            readAuthState: async () => ({
              checked: true,
              metaConnected: true,
              llmProviders: ["codex"],
            }),
          }
        )
      );

      assert.equal(code, 0, out.stdout + out.stderr);
      assert.match(out.stdout, /指定された接続だけ再認証します/);
      assert.doesNotMatch(out.stdout, /この AdDroid インスタンスの名前/);
      assert.match(out.stdout, /Codex config\s+:/);
      assert.match(out.stdout, /LLM Provider setup:/);
      assert.match(out.stdout, /configuring Codex app-server/);
      assert.deepEqual(authCalls, [["llm", "--provider", "codex"]]);
      const envRaw = fs.readFileSync(envFile, "utf8");
      assert.match(envRaw, /ADDROID_LLM_PROVIDER=codex/);
      assert.doesNotMatch(envRaw, /ADDROID_CODEX_DEFAULT_MODEL/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --non-interactive --yes は .env と workspace 名を初期化する", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    const prevMetaMock = process.env.ADDROID_META_ADS_CLI_MOCK;
    const prevGithubMock = process.env.ADDROID_GITHUB_OAUTH_MOCK;
    delete process.env.DATABASE_URL;
    delete process.env.ENCRYPTION_KEY;
    delete process.env.ADDROID_META_ADS_CLI_MOCK;
    delete process.env.ADDROID_GITHUB_OAUTH_MOCK;
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--non-interactive",
            "--yes",
            "--project-name",
            "Client Ads",
            "--database-url",
            "postgresql://addroid@localhost:5432/addroid",
            "--env-file",
            envFile,
            "--skip-db-create",
            "--skip-db-push",
            "--skip-deps",
            "--mock-integrations",
          ],
          {
            isTTY: false,
            randomBytes: () => Buffer.alloc(32, 1),
          }
        )
      );
      assert.equal(code, 0, out.stdout + out.stderr);

      const envRaw = fs.readFileSync(envFile, "utf8");
      assert.match(envRaw, /DATABASE_URL=postgresql:\/\/addroid@localhost:5432\/addroid/);
      assert.match(envRaw, /ENCRYPTION_KEY=AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=/);
      assert.doesNotMatch(envRaw, /ADDROID_META_ADS_CLI_MOCK=/);

      const configRaw = fs.readFileSync(path.join(home, "config.yaml"), "utf8");
      assert.match(configRaw, /slug: client-ads/);
      assert.match(configRaw, /displayName: Client Ads/);
      assert.match(configRaw, /urlRef: \(env\)/);
      assert.match(out.stdout, /env\s+:/);
      assert.match(out.stdout, /updated: DATABASE_URL, ENCRYPTION_KEY/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
      if (prevMetaMock === undefined) delete process.env.ADDROID_META_ADS_CLI_MOCK;
      else process.env.ADDROID_META_ADS_CLI_MOCK = prevMetaMock;
      if (prevGithubMock === undefined) delete process.env.ADDROID_GITHUB_OAUTH_MOCK;
      else process.env.ADDROID_GITHUB_OAUTH_MOCK = prevGithubMock;
    }
  });
});

test("init --interactive は prompt の回答で .env / config を作る", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    delete process.env.DATABASE_URL;
    delete process.env.ENCRYPTION_KEY;
    const answers = [
      "Agency Ops",
      "postgresql://addroid@localhost:5432/addroid",
      "codex-app-server",
      "Iv1.client123",
    ];
    const authCalls: string[][] = [];
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--interactive",
            "--skip-deps",
            "--skip-db-create",
            "--skip-db-push",
            "--env-file",
            envFile,
          ],
          {
            isTTY: true,
            prompt: async () => answers.shift() ?? "",
            confirm: async () => false,
            runAuthCommand: async (args) => {
              authCalls.push(args);
              return 0;
            },
            readAuthState: async () => ({
              checked: true,
              metaConnected: false,
              llmProviders: [],
            }),
            randomBytes: () => Buffer.alloc(32, 2),
          }
        )
      );
      assert.equal(code, 0, out.stdout + out.stderr);

      const envRaw = fs.readFileSync(envFile, "utf8");
      assert.match(envRaw, /DATABASE_URL=postgresql:\/\/addroid@localhost:5432\/addroid/);
      assert.match(envRaw, /ENCRYPTION_KEY=AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=/);
      assert.match(envRaw, /ADDROID_LLM_PROVIDER=codex/);
      const configRaw = fs.readFileSync(path.join(home, "config.yaml"), "utf8");
      assert.match(configRaw, /slug: agency-ops/);
      assert.match(configRaw, /displayName: Agency Ops/);
      assert.match(out.stdout, /Meta Access Token setup:/);
      assert.match(out.stdout, /実際の Meta 広告アカウント.*必須/);
      assert.match(out.stdout, /OAuth callback ではなく Access Token 入力方式/);
      assert.match(out.stdout, /HTTPS callback URL を用意する必要はありません/);
      assert.match(out.stdout, /token 入力後.*Ad Account.*選択/);
      assert.match(out.stdout, /Meta Token\s+: skipped/);
      assert.deepEqual(authCalls, [
        ["llm", "--provider", "codex"],
      ]);
      assert.match(out.stdout, /LLM Provider setup:/);
      assert.doesNotMatch(out.stdout, /LLM Provider を初期設定しますか/);
      assert.match(out.stdout, /Ready\./);
      assert.match(out.stdout, /addroid start/);
      assert.match(out.stdout, /addroid connect meta/);
      assert.doesNotMatch(out.stdout, /addroid accounts select/);
      assert.doesNotMatch(out.stdout, /addroid auth llm --provider openai/);
      assert.doesNotMatch(out.stdout, /addroid init --interactive --reauth-llm/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --interactive は初期画面に Integration check を表示する", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    delete process.env.DATABASE_URL;
    delete process.env.ENCRYPTION_KEY;
    const answers = [
      "Agency Ops",
      "postgresql://addroid@localhost:5432/addroid",
      "codex-app-server",
      "Iv1.client123",
    ];
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--interactive",
            "--skip-deps",
            "--skip-db-create",
            "--skip-db-push",
            "--env-file",
            envFile,
          ],
          {
            isTTY: true,
            prompt: async () => answers.shift() ?? "",
            confirm: async () => false,
            runAuthCommand: async () => 0,
            readAuthState: async () => ({
              checked: false,
              metaConnected: false,
              githubConnected: false,
              opsRepoLinked: false,
              llmProviders: [],
              detail: "DATABASE_URL or ENCRYPTION_KEY is not configured",
            }),
            randomBytes: () => Buffer.alloc(32, 3),
          }
        )
      );
      assert.equal(code, 0, out.stdout + out.stderr);
      assert.match(out.stdout, /Integration check:/);
      assert.match(out.stdout, /\[pending\] Meta Token\s+\.env \/ DB 作成後に init 内で token 入力 \+ Ad Account 選択を行います/);
      assert.match(out.stdout, /\[pending\] LLM Provider\s+\.env \/ DB 作成後に Codex app-server \/ OpenAI \/ Anthropic を選択して認証します/);
      assert.match(out.stdout, /\[pending\] GitHub \/ Ops Repo\s+\.env \/ DB 作成後に GitHub 認証 \+ ops repo 自動作成を行います/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --interactive は GitHub client id 未設定時に GitHub CLI browser auth へ進む", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    process.env.DATABASE_URL = "postgresql://addroid:secret@localhost:5432/addroid";
    process.env.ENCRYPTION_KEY = "AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM=";
    const answers = [
      "Agency Ops",
      "postgresql://addroid:secret@localhost:5432/addroid",
    ];
    const authCalls: string[][] = [];
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--interactive",
            "--skip-deps",
            "--skip-db-create",
            "--skip-db-push",
            "--env-file",
            envFile,
          ],
          {
            isTTY: true,
            prompt: async (_question, defaultValue = "") => answers.shift() ?? defaultValue,
            confirm: async () => true,
            runAuthCommand: async (args) => {
              authCalls.push(args);
              return 0;
            },
            readAuthState: async () => ({
              checked: true,
              metaConnected: true,
              metaAccountSelected: true,
              githubConnected: false,
              opsRepoLinked: false,
              llmProviders: ["codex"],
            }),
            randomBytes: () => Buffer.alloc(32, 4),
          }
        )
      );
      assert.equal(code, 0, out.stdout + out.stderr);
      assert.match(out.stdout, /GitHub OAuth : client id 未設定のため GitHub CLI のブラウザ認証を使用します/);
      assert.deepEqual(authCalls, [["github"]]);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --interactive は addroid コマンド未検出なら checkout CLI link を案内して実行する", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const calls: string[] = [];
    const env = {
      ...process.env,
      ADDROID_HOME: home,
      PATH: `${path.join(home, "node_modules", ".bin")}:/usr/bin:/bin`,
    } as NodeJS.ProcessEnv;
    delete env.DATABASE_URL;
    delete env.ENCRYPTION_KEY;

    const { code, out } = await capture(() =>
      runInit(
        [
          "--interactive",
          "--skip-deps",
          "--skip-db-create",
          "--skip-db-push",
          "--mock-integrations",
          "--env-file",
          envFile,
        ],
        {
          env,
          isTTY: true,
          prompt: async (_question, defaultValue = "") => defaultValue,
          confirm: async () => true,
          runCommand: (cmd, args) => {
            calls.push([cmd, ...args].join(" "));
            return { status: 0, stdout: "", stderr: "" };
          },
          randomBytes: () => Buffer.alloc(32, 9),
        }
      )
    );

    assert.equal(code, 0, out.stdout + out.stderr);
    assert.deepEqual(calls, []);
    assert.match(fs.readFileSync(path.join(home, "bin", "addroid"), "utf8"), /Generated by addroid init/);
    assert.match(out.stdout, /CLI command setup:/);
    assert.match(out.stdout, /addroid\s+: (created\/updated|available)/);
    assert.match(out.stdout, /addroid status/);
  });
});

test("init --interactive はインスタンス名を空 Enter にすると addroid を使う", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    delete process.env.DATABASE_URL;
    delete process.env.ENCRYPTION_KEY;
    const answers = [
      "",
      "postgresql://addroid@localhost:5432/addroid",
      "codex-app-server",
    ];
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--interactive",
            "--skip-deps",
            "--skip-db-create",
            "--skip-db-push",
            "--env-file",
            envFile,
          ],
          {
            isTTY: true,
            prompt: async (_question, defaultValue = "") => {
              const answer = answers.shift() ?? "";
              return answer.trim() ? answer : defaultValue;
            },
            confirm: async () => false,
            runAuthCommand: async () => 0,
            readAuthState: async () => ({
              checked: true,
              metaConnected: false,
              llmProviders: [],
            }),
            randomBytes: () => Buffer.alloc(32, 7),
          }
        )
      );
      assert.equal(code, 0, out.stdout + out.stderr);

      const configRaw = fs.readFileSync(path.join(home, "config.yaml"), "utf8");
      assert.match(configRaw, /slug: addroid/);
      assert.match(configRaw, /displayName: addroid/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --interactive は Meta Access Token 入力方式を案内し OAuth secret を要求しない", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const env = {
      ...process.env,
      ADDROID_HOME: home,
    } as NodeJS.ProcessEnv;
    delete env.DATABASE_URL;
    delete env.ENCRYPTION_KEY;
    const answers = [
      "Agency Ops",
      "postgresql://addroid:secret@localhost:5432/addroid",
      "codex-app-server",
    ];
    const metaRuntimeEnv: Array<{ databaseUrl?: string; encryptionKey?: string }> = [];

    const { code, out } = await capture(() =>
      runInit(
        [
          "--interactive",
          "--skip-deps",
          "--skip-db-create",
          "--skip-db-push",
          "--env-file",
          envFile,
        ],
        {
          env,
          isTTY: true,
          prompt: async () => answers.shift() ?? "",
          confirm: async (question) => question.includes("Meta Access Token"),
          runAuthCommand: async (args) => {
            if (args[0] === "meta") {
              metaRuntimeEnv.push({
                databaseUrl: process.env.DATABASE_URL,
                encryptionKey: process.env.ENCRYPTION_KEY,
              });
            }
            return 0;
          },
          readAuthState: async () => ({
            checked: true,
            metaConnected: false,
            llmProviders: [],
          }),
          randomBytes: () => Buffer.alloc(32, 8),
        }
      )
    );

    assert.equal(code, 0, out.stdout + out.stderr);
    const raw = fs.readFileSync(path.join(home, "secrets.local.yaml"), "utf8");
    assert.doesNotMatch(raw, /appId:/);
    assert.doesNotMatch(raw, /appSecret:/);
    assert.doesNotMatch(raw, /appIdCiphertext:/);
    assert.doesNotMatch(raw, /appSecretCiphertext:/);
    assert.match(out.stdout, /Meta Access Token setup:/);
    assert.match(out.stdout, /Meta Token\s+: ok/);
    assert.equal(metaRuntimeEnv[0]?.databaseUrl, "postgresql://addroid:secret@localhost:5432/addroid");
    assert.ok(metaRuntimeEnv[0]?.encryptionKey);
    assert.doesNotMatch(out.stdout, /Valid OAuth Redirect URIs/);
  });
});

test("init --non-interactive --db-push は Prisma setup を実行できる", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const calls: string[] = [];
    const prevDb = process.env.DATABASE_URL;
    const prevKey = process.env.ENCRYPTION_KEY;
    delete process.env.DATABASE_URL;
    delete process.env.ENCRYPTION_KEY;
    try {
      const { code, out } = await capture(() =>
        runInit(
          [
            "--non-interactive",
            "--yes",
            "--env-file",
            envFile,
            "--skip-db-create",
            "--skip-deps",
            "--db-push",
          ],
          {
            isTTY: false,
            randomBytes: () => Buffer.alloc(32, 3),
            runCommand: (cmd, args) => {
              calls.push([cmd, ...args].join(" "));
              return { status: 0, stdout: "", stderr: "" };
            },
          }
        )
      );
      assert.equal(code, 0, out.stdout + out.stderr);
      assert.deepEqual(calls.filter((c) => c.startsWith("npm ")), [
        "npm run db:generate",
        "npm run db:push -- --accept-data-loss",
      ]);
      assert.match(out.stdout, /Prisma schema\s+: ok/);
    } finally {
      if (prevDb === undefined) delete process.env.DATABASE_URL;
      else process.env.DATABASE_URL = prevDb;
      if (prevKey === undefined) delete process.env.ENCRYPTION_KEY;
      else process.env.ENCRYPTION_KEY = prevKey;
    }
  });
});

test("init --non-interactive --yes は --install-deps なしでは依存インストールを実行しない", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const calls: string[] = [];
    const env = {
      ...process.env,
      ADDROID_HOME: home,
      HOME: home,
      PATH: "/nonexistent-empty-path-9999",
    } as NodeJS.ProcessEnv;
    delete env.DATABASE_URL;
    delete env.ENCRYPTION_KEY;
    delete env.ADDROID_META_ADS_CLI_MOCK;
    delete env.ADDROID_GITHUB_OAUTH_MOCK;
    delete env.ADDROID_META_CLI_BIN;

    const { code, out } = await capture(() =>
      runInit(
        [
          "--non-interactive",
          "--yes",
          "--env-file",
          envFile,
          "--skip-db-create",
          "--skip-db-push",
        ],
        {
          env,
          isTTY: false,
          randomBytes: () => Buffer.alloc(32, 4),
          runCommand: (cmd, args) => {
            const line = [cmd, ...args].join(" ");
            calls.push(line);
            if (line.includes("command -v meta")) {
              return { status: 1, stdout: "", stderr: "" };
            }
            if (cmd === "psql") {
              return { status: 0, stdout: "", stderr: "" };
            }
            return { status: 1, stdout: "", stderr: "not found" };
          },
        }
      )
    );

    assert.equal(code, 0, out.stdout + out.stderr);
    assert.ok(!calls.some((c) => c.includes("tool install meta-ads --python 3.13")));
    const envRaw = fs.readFileSync(envFile, "utf8");
    assert.doesNotMatch(envRaw, /ADDROID_META_CLI_BIN=/);
    assert.doesNotMatch(out.stdout, /Meta Ads CLI\s+: ok - Meta Ads CLI installed/);
  });
});

test("init --non-interactive --install-deps は Meta Ads CLI を標準セットアップしない", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    const calls: string[] = [];
    const env = {
      ...process.env,
      ADDROID_HOME: home,
      HOME: home,
      PATH: "/nonexistent-empty-path-9999",
    } as NodeJS.ProcessEnv;
    delete env.DATABASE_URL;
    delete env.ENCRYPTION_KEY;
    delete env.ADDROID_META_ADS_CLI_MOCK;
    delete env.ADDROID_META_CLI_BIN;

    const { code, out } = await capture(() =>
      runInit(
        [
          "--non-interactive",
          "--install-deps",
          "--env-file",
          envFile,
          "--skip-db-create",
          "--skip-db-push",
        ],
        {
          env,
          isTTY: false,
          randomBytes: () => Buffer.alloc(32, 5),
          runCommand: (cmd, args) => {
            const line = [cmd, ...args].join(" ");
            calls.push(line);
            if (cmd === "brew" && line === "brew --version") {
              return { status: 0, stdout: "", stderr: "" };
            }
            if (cmd === "brew" && line === "brew --prefix postgresql@16") {
              return { status: 0, stdout: "/opt/homebrew/opt/postgresql@16\n", stderr: "" };
            }
            if (cmd === "brew" && line === "brew services list") {
              return {
                status: 0,
                stdout: "Name          Status  User File\npostgresql@14 started inaba ~/Library/LaunchAgents/homebrew.mxcl.postgresql@14.plist\n",
                stderr: "",
              };
            }
            if (cmd === "brew") {
              return { status: 0, stdout: "", stderr: "" };
            }
            if (cmd === "sh" && line.includes("command -v apt-get")) {
              return { status: 0, stdout: "", stderr: "" };
            }
            if (cmd === "sh" && line.includes("sudo apt-get")) {
              return { status: 0, stdout: "", stderr: "" };
            }
            if (cmd === "sh" && line.includes("command -v dnf")) {
              return { status: 1, stdout: "", stderr: "" };
            }
            if (cmd === "psql") {
              return { status: 0, stdout: "160010\n", stderr: "" };
            }
            return { status: 1, stdout: "", stderr: "not found" };
          },
        }
      )
    );

    assert.equal(code, 0, out.stdout + out.stderr);
    assert.match(out.stdout, /Dependency setup:/);
    if (process.platform === "darwin") {
      assert.ok(calls.some((c) => c === "brew services stop postgresql@14"));
      assert.ok(calls.some((c) => c === "brew services start postgresql@16"));
      assert.match(env.PATH ?? "", /postgresql@16\/bin/);
    }
    assert.ok(!calls.some((c) => c.includes("tool install meta-ads")));
    assert.doesNotMatch(out.stdout, /Meta Ads CLI/);
    assert.doesNotMatch(fs.readFileSync(envFile, "utf8"), /ADDROID_META_CLI_BIN=/);
  });
});

test("init --non-interactive --yes は既定 DATABASE_URL にランダム password を入れ DB role に設定する", async () => {
  await withTempHome(async (home) => {
    const envFile = path.join(home, ".env");
    let psqlInput = "";
    const env = {
      ...process.env,
      ADDROID_HOME: home,
      HOME: home,
    } as NodeJS.ProcessEnv;
    delete env.DATABASE_URL;
    delete env.ENCRYPTION_KEY;
    delete env.ADDROID_META_ADS_CLI_MOCK;
    delete env.ADDROID_META_CLI_BIN;

    const { code, out } = await capture(() =>
      runInit(
        [
          "--non-interactive",
          "--yes",
          "--env-file",
          envFile,
          "--skip-deps",
          "--skip-db-push",
        ],
        {
          env,
          isTTY: false,
          randomBytes: (size) => Buffer.alloc(size, 6),
          runCommand: (cmd, args, opts) => {
            if ([cmd, ...args].join(" ").includes("command -v meta")) {
              return { status: 1, stdout: "", stderr: "" };
            }
            if (cmd === "psql") {
              psqlInput = opts?.input ?? "";
              return { status: 0, stdout: "", stderr: "" };
            }
            return { status: 1, stdout: "", stderr: "not found" };
          },
        }
      )
    );

    assert.equal(code, 0, out.stdout + out.stderr);
    const envRaw = fs.readFileSync(envFile, "utf8");
    assert.match(envRaw, /DATABASE_URL=postgresql:\/\/addroid:[A-Za-z0-9_-]+@localhost:5432\/addroid/);
    assert.match(psqlInput, /CREATE ROLE addroid LOGIN PASSWORD '[A-Za-z0-9_-]+'/);
    assert.match(psqlInput, /ALTER ROLE addroid WITH LOGIN PASSWORD '[A-Za-z0-9_-]+'/);
    assert.match(psqlInput, /ALTER SCHEMA public OWNER TO addroid/);
    assert.doesNotMatch(psqlInput, /CREATE ROLE addroid LOGIN;/);
  });
});
